In [41]:
pip install tmdbsimple

Requirement already satisfied: tmdbsimple in /usr/local/lib/python3.10/dist-packages (2.9.1)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from tmdbsimple) (2.27.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->tmdbsimple) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->tmdbsimple) (2023.5.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests->tmdbsimple) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->tmdbsimple) (3.4)

In [42]:
!python -m pip install requests

Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (2.27.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests) (2023.5.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests) (3.4)

In [43]:
#Api Read Acces Token
#eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJjZWRmZGE4NTliNjUwYjI5ZjU2YWYyZDZhZTg2NThkNiIsInN1YiI6IjY0MWRlZWNiYzk5ODI2MDBiYTQ3NTg3NCIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.nhRFhmi621MstknliXTrfntO7a-n8tv7KAe5mytJ_Qw

#Api Key
#cedfda859b650b29f56af2d6ae8658d6

In [44]:
import tmdbsimple as tmdb
tmdb.API_KEY = 'cedfda859b650b29f56af2d6ae8658d6'

In [45]:
import requests
tmdb.REQUESTS_SESSION = requests.Session()

In [46]:
import tmdbsimple as tmdb
tmdb.API_KEY = 'cedfda859b650b29f56af2d6ae8658d6'

movie = tmdb.Movies(268) # Batman Collection (1999)
response = movie.info()

# Imprime información detallada sobre la película
print(response)

{'adult': False, 'backdrop_path': '/frDS8A5vIP927KYAxTVVKRIbqZw.jpg', 'belongs_to_collection': {'id': 120794, 'name': 'Batman Collection', 'poster_path': '/4AUoqt72CVP4UV902hmdDj4t5Q9.jpg', 'backdrop_path': '/4UHZWw5lV3ZoadTjXuVOakdH32L.jpg'}, 'budget': 35000000, 'genres': [{'id': 14, 'name': 'Fantasy'}, {'id': 28, 'name': 'Action'}, {'id': 80, 'name': 'Crime'}], 'homepage': '', 'id': 268, 'imdb_id': 'tt0096895', 'original_language': 'en', 'original_title': 'Batman', 'overview': 'Batman must face his most ruthless nemesis when a deformed madman calling himself "The Joker" seizes control of Gotham\'s criminal underworld.', 'popularity': 50.014, 'poster_path': '/cij4dd21v2Rk2YtUQbV5kW69WB2.jpg', 'production_companies': [{'id': 4357, 'logo_path': None, 'name': 'The Guber-Peters Company', 'origin_country': ''}, {'id': 174, 'logo_path': '/IuAlhI9eVC9Z8UQWOIDdWRKSEJ.png', 'name': 'Warner Bros. Pictures', 'origin_country': 'US'}, {'id': 1382, 'logo_path': '/sOg7LGESPH5vCTOIdbMhLuypoLL.png', 'name': 'PolyGram Filmed Entertainment', 'origin_country': 'US'}, {'id': 429, 'logo_path': '/2Tc1P3Ac8M479naPp1kYT3izLS5.png', 'name': 'DC Comics', 'origin_country': 'US'}], 'production_countries': [{'iso_3166_1': 'US', 'name': 'United States of America'}], 'release_date': '1989-06-23', 'revenue': 411348924, 'runtime': 126, 'spoken_languages': [{'english_name': 'English', 'iso_639_1': 'en', 'name': 'English'}, {'english_name': 'French', 'iso_639_1': 'fr', 'name': 'Français'}], 'status': 'Released', 'tagline': 'Have you ever danced with the devil in the pale moonlight?', 'title': 'Batman', 'video': False, 'vote_average': 7.212, 'vote_count': 6997}

In [47]:
import tmdbsimple as tmdb
tmdb.API_KEY = 'cedfda859b650b29f56af2d6ae8658d6'

search = tmdb.Search()
response = search.movie(query='movies')

for result in response['results']:
    movie = tmdb.Movies(result['id'])
    movie_info = movie.info()
    print(result['title'], movie_info['runtime'])

Movies 0
Movies 0
Sword Art Online the Movie -Progressive- Scherzo of Deep Night 100
Movies 0
Miraculous: Ladybug & Cat Noir, The Movie 107
Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train 117
That Time I Got Reincarnated as a Slime the Movie: Scarlet Bond 108
The Quintessential Quintuplets Movie 136
The Ten Commandments: The Movie 120
Naruto Shippuden the Movie 94
The Last: Naruto the Movie 114
X-Rated: The Greatest Adult Movies of All Time 94
Pokémon the Movie: Secrets of the Jungle 101
Boruto: Naruto the Movie 95
A Silent Voice: The Movie 130
Naruto Shippuden the Movie: Blood Prison 108
Easy Sex, Sad Movies 90
Sailor Moon SuperS: The Movie: Black Dream Hole 60
Road to Ninja: Naruto the Movie 109
Kuroko's Basketball the Movie: Last Game 90

In [48]:
import tmdbsimple as tmdb
import pandas as pd

tmdb.API_KEY = 'cedfda859b650b29f56af2d6ae8658d6'

search = tmdb.Search()
response = search.movie(query='movies')

movies = []
for result in response['results']:
    movie = {
        'title': result['title'],
        'release_date': result['release_date'],
        'popularity': result['popularity']
    }
    movies.append(movie)

df = pd.DataFrame(movies)
print(df)

                                                title release_date  popularity
0                                              Movies                    1.546
1                                              Movies                    0.600
2   Sword Art Online the Movie -Progressive- Scher...   2022-10-22     247.353
3                                              Movies                    0.600
4           Miraculous: Ladybug & Cat Noir, The Movie   2023-07-05     304.840
5   Demon Slayer -Kimetsu no Yaiba- The Movie: Mug...   2020-10-16     132.360
6   That Time I Got Reincarnated as a Slime the Mo...   2022-11-25     138.136
7                The Quintessential Quintuplets Movie   2022-05-20      91.576
8                     The Ten Commandments: The Movie   2016-01-28      26.888
9                          Naruto Shippuden the Movie   2007-08-04      79.180
10                         The Last: Naruto the Movie   2014-12-06      51.872
11     X-Rated: The Greatest Adult Movies of All Time   2015-02-06      39.319
12           Pokémon the Movie: Secrets of the Jungle   2020-12-25      40.206
13                           Boruto: Naruto the Movie   2015-08-07      49.800
14                          A Silent Voice: The Movie   2016-09-17      50.390
15           Naruto Shippuden the Movie: Blood Prison   2011-07-30      45.508
16                               Easy Sex, Sad Movies   2014-10-16       9.055
17    Sailor Moon SuperS: The Movie: Black Dream Hole   1995-12-23      31.413
18                    Road to Ninja: Naruto the Movie   2012-07-28      46.581
19           Kuroko's Basketball the Movie: Last Game   2017-03-18      19.732

In [49]:
import tmdbsimple as tmdb
import pandas as pd

tmdb.API_KEY = 'cedfda859b650b29f56af2d6ae8658d6'

search = tmdb.Search()
movies = []
for page in range(1, 10):
    response = search.movie(query='movies', page=page)
    for result in response['results']:
        movie_id = result['id']
        movie_details = tmdb.Movies(movie_id).info()
        movie = {
            'title': result['title'],
            'release_date': result['release_date'],
            'popularity': result['popularity'],
            'genres': [genre['name'] for genre in movie_details['genres']],
            'budget': movie_details['budget'],
            'revenue': movie_details['revenue'],
            'vote_average': movie_details['vote_average'],
            'runtime': movie_details['runtime']
        }
        movies.append(movie)

df = pd.DataFrame(movies)
print(df)

                                                 title release_date  \
0                                               Movies
1                                               Movies
2    Sword Art Online the Movie -Progressive- Scher...   2022-10-22
3                                               Movies
4            Miraculous: Ladybug & Cat Noir, The Movie   2023-07-05
..                                                 ...          ...
175                        The New Employee: The Movie   2023-04-30
176  THE iDOLM@STER MOVIE: Beyond the Brilliant Fut...   2014-01-25
177                         Yowamushi Pedal: The Movie   2015-08-28
178                       Break the Silence: The Movie   2020-09-10
179                         Animal Crossing: The Movie   2006-12-16

     popularity                                         genres    budget  \
0         1.546                                             []         0
1         0.600                                             []         0
2       247.353  [Animation, Action, Fantasy, Science Fiction]         0
3         0.600                                             []         0
4       304.840  [Animation, Family, Action, Fantasy, Romance]  86000000
..          ...                                            ...       ...
175       0.600                                      [Romance]         0
176       5.082                      [Animation, Drama, Music]         0
177       4.819                            [Action, Animation]         0
178       7.710                           [Music, Documentary]         0
179      11.992                     [Animation, Drama, Family]         0

     revenue  vote_average  runtime
0          0           4.2        0
1          0           1.7        0
2          0           7.6      100
3          0           0.0        0
4          0           8.6      107
..       ...           ...      ...
175        0           0.0      115
176        0           5.6      122
177        0           7.6       90
178  8954945           9.2       90
179        0           6.9       87

[180 rows x 8 columns]

In [50]:
print(df.to_string())

                                                                                                  title release_date  popularity                                                                    genres     budget    revenue  vote_average  runtime
0                                                                                                Movies                    1.546                                                                        []          0          0         4.200        0
1                                                                                                Movies                    0.600                                                                        []          0          0         1.700        0
2                                        Sword Art Online the Movie -Progressive- Scherzo of Deep Night   2022-10-22     247.353                             [Animation, Action, Fantasy, Science Fiction]          0          0         7.600      100
3                                                                                                Movies                    0.600                                                                        []          0          0         0.000        0
4                                                             Miraculous: Ladybug & Cat Noir, The Movie   2023-07-05     304.840                             [Animation, Family, Action, Fantasy, Romance]   86000000          0         8.600      107
5                                                Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train   2020-10-16     132.360                         [Action, Animation, Adventure, Fantasy, Thriller]   15800000  503063688         8.256      117
6                                       That Time I Got Reincarnated as a Slime the Movie: Scarlet Bond   2022-11-25     138.136                                           [Animation, Fantasy, Adventure]          0   11426555         7.600      108
7                                                                  The Quintessential Quintuplets Movie   2022-05-20      91.576                                              [Animation, Comedy, Romance]          0   17288993         8.407      136
8                                                                       The Ten Commandments: The Movie   2016-01-28      26.888                                                                   [Drama]   39307171   37070177         7.200      120
9                                                                            Naruto Shippuden the Movie   2007-08-04      79.180                                              [Animation, Action, Fantasy]          0   10000000         7.274       94
10                                                                           The Last: Naruto the Movie   2014-12-06      51.872                                              [Action, Romance, Animation]     903852   19840000         7.749      114
11                                                       X-Rated: The Greatest Adult Movies of All Time   2015-02-06      39.319                                                             [Documentary]          0          0         6.147       94
12                                                             Pokémon the Movie: Secrets of the Jungle   2020-12-25      40.206                                   [Animation, Adventure, Family, Fantasy]          0          0         7.100      101
13                                                                             Boruto: Naruto the Movie   2015-08-07      49.800                                               [Animation, Action, Comedy]          0   39500000         7.594       95
14                                                                            A Silent Voice: The Movie   2016-09-17      50.390                                                        [Animation, Drama]          0   30156463         8.400      130
15                                                             Naruto Shippuden the Movie: Blood Prison   2011-07-30      45.508                    [Thriller, Animation, Action, Comedy, Horror, Mystery]          0    9100000         7.292      108
16                                                                                 Easy Sex, Sad Movies   2014-10-16       9.055                                                                  [Comedy]          0          0         5.500       90
17                                                      Sailor Moon SuperS: The Movie: Black Dream Hole   1995-12-23      31.413                             [Animation, Fantasy, Action, Romance, Comedy]          0          0         8.100       60
18                                                                      Road to Ninja: Naruto the Movie   2012-07-28      46.581                                              [Animation, Fantasy, Action]          0   17900000         7.576      109
19                                                             Kuroko's Basketball the Movie: Last Game   2017-03-18      19.732                                                               [Animation]          0          0         7.745       90
20                                                                    Naruto Shippuden the Movie: Bonds   2008-08-02      35.180                                              [Fantasy, Animation, Action]          0   10600000         7.185       90
21                                                                     Pokémon the Movie: I Choose You!   2017-07-15      32.357                                   [Family, Animation, Adventure, Fantasy]          0   37552144         7.026       98
22                                                                                    The Rugrats Movie   1998-11-20      24.231                                    [Family, Animation, Comedy, Adventure]   30000000  100491683         6.173       79
23                                                                 Teasing Master Takagi-san: The Movie   2022-06-10      22.342                                              [Animation, Comedy, Romance]          0          0         8.500       73
24                                                                         Violet Evergarden: The Movie   2020-09-18      33.598                                      [Animation, Fantasy, Romance, Drama]          0   20339624         8.300      140
25                                                       Pokémon the Movie: Hoopa and the Clash of Ages   2015-07-18      30.008                           [Family, Adventure, Animation, Action, Fantasy]  150000000          0         6.755       73
26                                    Sword Art Online the Movie -Progressive- Aria of a Starless Night   2021-10-30      31.840                             [Animation, Action, Fantasy, Science Fiction]          0   14037060         7.800       97
27                                                   Pokémon the Movie: Mewtwo Strikes Back - Evolution   2019-07-12      50.250                           [Animation, Adventure, Fantasy, Action, Family]          0   26654184         6.700       98
28                                                           Naruto Shippuden the Movie: The Lost Tower   2010-07-31      37.216                                            [Adventure, Action, Animation]          0    8500000         6.996       85
29                                                                Student Council Staff Members Movie 2   2021-01-01      28.219                                                       [Animation, Comedy]          0          0         6.200       78
30                                             Naruto the Movie: Guardians of the Crescent Moon Kingdom   2006-08-05      32.030                                            [Adventure, Animation, Action]          0    3224000         7.059       95
31                                                                       Kinmoza the Movie: Thank You!!   2021-08-20       7.160                                                       [Animation, Comedy]          0          0         4.500       82
32                                                                             Pokémon: The First Movie   1998-07-18      25.994                           [Animation, Family, Adventure, Fantasy, Action]   30000000  163644662         6.905       85
33                                                    Naruto the Movie: Ninja Clash in the Land of Snow   2004-08-21      32.376                                    [Comedy, Action, Animation, Adventure]          0   17400000         7.221       82
34                                                                                 One Piece: The Movie   2000-03-04      22.806                           [Action, Animation, Adventure, Comedy, Fantasy]          0          0         6.993       51
35                                                   Inuyasha the Movie 3: Swords of an Honorable Ruler   2003-12-20      38.018                                           [Animation, Fantasy, Adventure]          0          0         7.800       99
36                                                                        Teen Titans Go! To the Movies   2018-07-27      22.820                              [Animation, Action, Comedy, Science Fiction]   10000000   28646544         7.352       84
37                                                  Inuyasha the Movie: Affections Touching Across Time   2001-12-15      35.905                                   [Action, Animation, Adventure, Fantasy]      10540          0         7.671       99
38                                                                    Saga of Tanya the Evil: The Movie   2019-02-08      16.541                                         [Animation, Action, War, Fantasy]          0          0         8.094       98
39                                                              Student Council Staff Members the Movie   2017-07-21      25.293                                                       [Animation, Comedy]          0          0         6.300       60
40                                               Pokémon the Movie: Volcanion and the Mechanical Marvel   2016-07-16      19.234                  [Family, Adventure, Animation, Fantasy, Science Fiction]          0          0         6.761       97
41                                                       Naruto the Movie: Legend of the Stone of Gelel   2005-08-06      26.582                                           [Animation, Adventure, Fantasy]          0   10200000         6.561       96
42                                                      Inuyasha the Movie 4: Fire on the Mystic Island   2004-12-23      25.439                                           [Fantasy, Animation, Adventure]          0          0         7.500       88
43                                                         Naruto Shippuden the Movie: The Will of Fire   2009-08-01      34.196                    [Action, Adventure, Comedy, Drama, Fantasy, Animation]          0    8084148         7.205       95
44                                                 Pretty Guardian Sailor Moon Eternal The Movie Part 1   2021-01-08      23.195                                              [Animation, Action, Fantasy]          0          0         7.800       80
45                                                                               Pokémon the Movie 2000   1999-07-17      20.882                  [Adventure, Fantasy, Animation, Science Fiction, Family]   30000000  163649270         6.660       84
46                                          Kuroko's Basketball - Movie: Winter Cup - Crossing the Door   2016-12-03      10.364                                                               [Animation]          0          0         7.500       90
47                                                                         Cardcaptor Sakura: The Movie   1999-08-21      18.377                            [Fantasy, Animation, Adventure, Action, Drama]          0          0         7.690       81
48                                                Fullmetal Alchemist the Movie: Conqueror of Shamballa   2005-07-21      23.564                                     [Action, Adventure, Animation, Drama]          0          0         7.251      105
49                                                                         Bleach the Movie: Hell Verse   2010-12-04      15.796                                   [Action, Animation, Fantasy, Adventure]          0    8749681         7.571       94
50                                                   Pokémon the Movie: Kyurem vs. the Sword of Justice   2012-07-13      17.984          [Family, Animation, Action, Adventure, Fantasy, Science Fiction]          0   44057737         6.400       71
51                                                  Pretty Guardian Sailor Moon Cosmos The Movie Part 2   2023-06-30      27.249                                                               [Animation]          0          0         0.000        0
52                                                 Pretty Guardian Sailor Moon Eternal The Movie Part 2   2021-02-11      21.851           [Animation, Action, Adventure, Comedy, Drama, Fantasy, Romance]          0          0         8.100       80
53                                                          Sword Art Online: The Movie – Ordinal Scale   2017-02-18      24.823         [Animation, Action, Adventure, Fantasy, Romance, Science Fiction]          0   20725409         7.753      119
54                                            Inuyasha the Movie 2: The Castle Beyond the Looking Glass   2002-12-22      29.067                                   [Action, Animation, Adventure, Fantasy]          0          0         7.700      100
55                                                                      Bleach the Movie: Fade to Black   2008-12-13      18.882                                       [Action, Animation, Fantasy, Drama]          0    6032296         7.106       94
56                                                                             Sailor Moon R: The Movie   1993-12-05      22.491                                     [Animation, Romance, Action, Fantasy]          0   12307555         8.000       61
57                                                  Pretty Guardian Sailor Moon Cosmos The Movie Part 1   2023-06-09      45.604                                                               [Animation]          0          0         0.000        0
58                                                                             Laid-Back Camp The Movie   2022-07-01      17.384                                                       [Animation, Comedy]          0    7283918         7.500      121
59                                    Ranma ½: The Movie 2 — The Battle of Togenkyo: Rescue the Brides!   1992-08-02      39.016                                               [Action, Comedy, Animation]          0          0         8.000       63
60                                                      Pokémon the Movie: Black - Victini and Reshiram   2011-07-16      16.244                            [Animation, Family, Adventure, Drama, Fantasy]          0          0         6.600       96
61                                                             Grateful Dead Meet-Up At The Movies 2023   2023-06-22       3.803                                                      [Documentary, Music]          0          0         0.000        0
62                                                                              Cowboy Bebop: The Movie   2001-09-01      16.944                                      [Action, Animation, Science Fiction]          0          0         7.692      115
63                                                                               Psycho-Pass: The Movie   2015-01-09      10.628                                      [Animation, Science Fiction, Action]          0          0         7.108      113
64                                                                   Pokémon the Movie: The Power of Us   2018-07-13      14.961                                   [Animation, Family, Adventure, Fantasy]          0   23740788         7.100       98
65                                                                                 Pokémon 3: The Movie   2000-07-08      17.642                           [Adventure, Fantasy, Animation, Action, Family]   16000000   68411275         6.503       74
66                                                                                   2gether: The Movie   2021-04-22      12.009                                                          [Drama, Romance]          0          0         7.900      107
67                                                                             Sekaiichi Hatsukoi Movie   2014-03-15       8.554                                               [Animation, Romance, Drama]          0          0         6.700       50
68                                           Gintama: The Movie: The Final Chapter: Be Forever Yorozuya   2013-07-04      15.727                              [Action, Comedy, Science Fiction, Animation]          0          0         8.000      110
69                                                               Sailor Moon S the Movie: Hearts in Ice   1994-12-04      27.284                             [Animation, Fantasy, Action, Romance, Comedy]          0    9940717         7.823       60
70                                                                 Bleach the Movie: Memories of Nobody   2006-12-16      15.143                                     [Fantasy, Animation, Science Fiction]          0    1238072         6.922       87
71                                                                              Cherry Magic! THE MOVIE   2022-04-08      23.381                                                         [Comedy, Romance]          0          0         7.000      104
72                                                       Haikyuu!! The Movie: The End and the Beginning   2015-07-03      11.148                                                [Animation, Comedy, Drama]          0          0         8.400       89
73                                              Fullmetal Alchemist the Movie: The Sacred Star of Milos   2011-07-02      11.455                  [Adventure, Fantasy, Animation, Action, Science Fiction]          0    7401480         6.830      110
74                                                        Pokémon the Movie: White - Victini and Zekrom   2011-07-16      15.279                            [Animation, Family, Adventure, Drama, Fantasy]          0          0         6.600       96
75   Ranma ½: The Movie 3 — The Super Non-Discriminatory Showdown: Team Ranma vs. the Legendary Phoenix   1994-08-20      43.318                                                       [Animation, Comedy]          0          0         7.700       35
76                                                          Bleach the Movie: The DiamondDust Rebellion   2007-12-22      15.894                                            [Action, Adventure, Animation]          0          0         6.717       95
77                                                                Street Fighter II: The Animated Movie   1994-08-06      18.465                                                       [Animation, Action]          0          0         6.900      101
78                                                                              Just Like in the Movies   1989-10-04       1.020                                                           [Comedy, Drama]          0          0         8.000       92

In [51]:
print(df.iloc[0:100].to_string())

                                                                                                 title release_date  popularity                                                             genres     budget    revenue  vote_average  runtime
0                                                                                               Movies                    1.546                                                                 []          0          0         4.200        0
1                                                                                               Movies                    0.600                                                                 []          0          0         1.700        0
2                                       Sword Art Online the Movie -Progressive- Scherzo of Deep Night   2022-10-22     247.353                      [Animation, Action, Fantasy, Science Fiction]          0          0         7.600      100
3                                                                                               Movies                    0.600                                                                 []          0          0         0.000        0
4                                                            Miraculous: Ladybug & Cat Noir, The Movie   2023-07-05     304.840                      [Animation, Family, Action, Fantasy, Romance]   86000000          0         8.600      107
5                                               Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train   2020-10-16     132.360                  [Action, Animation, Adventure, Fantasy, Thriller]   15800000  503063688         8.256      117
6                                      That Time I Got Reincarnated as a Slime the Movie: Scarlet Bond   2022-11-25     138.136                                    [Animation, Fantasy, Adventure]          0   11426555         7.600      108
7                                                                 The Quintessential Quintuplets Movie   2022-05-20      91.576                                       [Animation, Comedy, Romance]          0   17288993         8.407      136
8                                                                      The Ten Commandments: The Movie   2016-01-28      26.888                                                            [Drama]   39307171   37070177         7.200      120
9                                                                           Naruto Shippuden the Movie   2007-08-04      79.180                                       [Animation, Action, Fantasy]          0   10000000         7.274       94
10                                                                          The Last: Naruto the Movie   2014-12-06      51.872                                       [Action, Romance, Animation]     903852   19840000         7.749      114
11                                                      X-Rated: The Greatest Adult Movies of All Time   2015-02-06      39.319                                                      [Documentary]          0          0         6.147       94
12                                                            Pokémon the Movie: Secrets of the Jungle   2020-12-25      40.206                            [Animation, Adventure, Family, Fantasy]          0          0         7.100      101
13                                                                            Boruto: Naruto the Movie   2015-08-07      49.800                                        [Animation, Action, Comedy]          0   39500000         7.594       95
14                                                                           A Silent Voice: The Movie   2016-09-17      50.390                                                 [Animation, Drama]          0   30156463         8.400      130
15                                                            Naruto Shippuden the Movie: Blood Prison   2011-07-30      45.508             [Thriller, Animation, Action, Comedy, Horror, Mystery]          0    9100000         7.292      108
16                                                                                Easy Sex, Sad Movies   2014-10-16       9.055                                                           [Comedy]          0          0         5.500       90
17                                                     Sailor Moon SuperS: The Movie: Black Dream Hole   1995-12-23      31.413                      [Animation, Fantasy, Action, Romance, Comedy]          0          0         8.100       60
18                                                                     Road to Ninja: Naruto the Movie   2012-07-28      46.581                                       [Animation, Fantasy, Action]          0   17900000         7.576      109
19                                                            Kuroko's Basketball the Movie: Last Game   2017-03-18      19.732                                                        [Animation]          0          0         7.745       90
20                                                                   Naruto Shippuden the Movie: Bonds   2008-08-02      35.180                                       [Fantasy, Animation, Action]          0   10600000         7.185       90
21                                                                    Pokémon the Movie: I Choose You!   2017-07-15      32.357                            [Family, Animation, Adventure, Fantasy]          0   37552144         7.026       98
22                                                                                   The Rugrats Movie   1998-11-20      24.231                             [Family, Animation, Comedy, Adventure]   30000000  100491683         6.173       79
23                                                                Teasing Master Takagi-san: The Movie   2022-06-10      22.342                                       [Animation, Comedy, Romance]          0          0         8.500       73
24                                                                        Violet Evergarden: The Movie   2020-09-18      33.598                               [Animation, Fantasy, Romance, Drama]          0   20339624         8.300      140
25                                                      Pokémon the Movie: Hoopa and the Clash of Ages   2015-07-18      30.008                    [Family, Adventure, Animation, Action, Fantasy]  150000000          0         6.755       73
26                                   Sword Art Online the Movie -Progressive- Aria of a Starless Night   2021-10-30      31.840                      [Animation, Action, Fantasy, Science Fiction]          0   14037060         7.800       97
27                                                  Pokémon the Movie: Mewtwo Strikes Back - Evolution   2019-07-12      50.250                    [Animation, Adventure, Fantasy, Action, Family]          0   26654184         6.700       98
28                                                          Naruto Shippuden the Movie: The Lost Tower   2010-07-31      37.216                                     [Adventure, Action, Animation]          0    8500000         6.996       85
29                                                               Student Council Staff Members Movie 2   2021-01-01      28.219                                                [Animation, Comedy]          0          0         6.200       78
30                                            Naruto the Movie: Guardians of the Crescent Moon Kingdom   2006-08-05      32.030                                     [Adventure, Animation, Action]          0    3224000         7.059       95
31                                                                      Kinmoza the Movie: Thank You!!   2021-08-20       7.160                                                [Animation, Comedy]          0          0         4.500       82
32                                                                            Pokémon: The First Movie   1998-07-18      25.994                    [Animation, Family, Adventure, Fantasy, Action]   30000000  163644662         6.905       85
33                                                   Naruto the Movie: Ninja Clash in the Land of Snow   2004-08-21      32.376                             [Comedy, Action, Animation, Adventure]          0   17400000         7.221       82
34                                                                                One Piece: The Movie   2000-03-04      22.806                    [Action, Animation, Adventure, Comedy, Fantasy]          0          0         6.993       51
35                                                  Inuyasha the Movie 3: Swords of an Honorable Ruler   2003-12-20      38.018                                    [Animation, Fantasy, Adventure]          0          0         7.800       99
36                                                                       Teen Titans Go! To the Movies   2018-07-27      22.820                       [Animation, Action, Comedy, Science Fiction]   10000000   28646544         7.352       84
37                                                 Inuyasha the Movie: Affections Touching Across Time   2001-12-15      35.905                            [Action, Animation, Adventure, Fantasy]      10540          0         7.671       99
38                                                                   Saga of Tanya the Evil: The Movie   2019-02-08      16.541                                  [Animation, Action, War, Fantasy]          0          0         8.094       98
39                                                             Student Council Staff Members the Movie   2017-07-21      25.293                                                [Animation, Comedy]          0          0         6.300       60
40                                              Pokémon the Movie: Volcanion and the Mechanical Marvel   2016-07-16      19.234           [Family, Adventure, Animation, Fantasy, Science Fiction]          0          0         6.761       97
41                                                      Naruto the Movie: Legend of the Stone of Gelel   2005-08-06      26.582                                    [Animation, Adventure, Fantasy]          0   10200000         6.561       96
42                                                     Inuyasha the Movie 4: Fire on the Mystic Island   2004-12-23      25.439                                    [Fantasy, Animation, Adventure]          0          0         7.500       88
43                                                        Naruto Shippuden the Movie: The Will of Fire   2009-08-01      34.196             [Action, Adventure, Comedy, Drama, Fantasy, Animation]          0    8084148         7.205       95
44                                                Pretty Guardian Sailor Moon Eternal The Movie Part 1   2021-01-08      23.195                                       [Animation, Action, Fantasy]          0          0         7.800       80
45                                                                              Pokémon the Movie 2000   1999-07-17      20.882           [Adventure, Fantasy, Animation, Science Fiction, Family]   30000000  163649270         6.660       84
46                                         Kuroko's Basketball - Movie: Winter Cup - Crossing the Door   2016-12-03      10.364                                                        [Animation]          0          0         7.500       90
47                                                                        Cardcaptor Sakura: The Movie   1999-08-21      18.377                     [Fantasy, Animation, Adventure, Action, Drama]          0          0         7.690       81
48                                               Fullmetal Alchemist the Movie: Conqueror of Shamballa   2005-07-21      23.564                              [Action, Adventure, Animation, Drama]          0          0         7.251      105
49                                                                        Bleach the Movie: Hell Verse   2010-12-04      15.796                            [Action, Animation, Fantasy, Adventure]          0    8749681         7.571       94
50                                                  Pokémon the Movie: Kyurem vs. the Sword of Justice   2012-07-13      17.984   [Family, Animation, Action, Adventure, Fantasy, Science Fiction]          0   44057737         6.400       71
51                                                 Pretty Guardian Sailor Moon Cosmos The Movie Part 2   2023-06-30      27.249                                                        [Animation]          0          0         0.000        0
52                                                Pretty Guardian Sailor Moon Eternal The Movie Part 2   2021-02-11      21.851    [Animation, Action, Adventure, Comedy, Drama, Fantasy, Romance]          0          0         8.100       80
53                                                         Sword Art Online: The Movie – Ordinal Scale   2017-02-18      24.823  [Animation, Action, Adventure, Fantasy, Romance, Science Fiction]          0   20725409         7.753      119
54                                           Inuyasha the Movie 2: The Castle Beyond the Looking Glass   2002-12-22      29.067                            [Action, Animation, Adventure, Fantasy]          0          0         7.700      100
55                                                                     Bleach the Movie: Fade to Black   2008-12-13      18.882                                [Action, Animation, Fantasy, Drama]          0    6032296         7.106       94
56                                                                            Sailor Moon R: The Movie   1993-12-05      22.491                              [Animation, Romance, Action, Fantasy]          0   12307555         8.000       61
57                                                 Pretty Guardian Sailor Moon Cosmos The Movie Part 1   2023-06-09      45.604                                                        [Animation]          0          0         0.000        0
58                                                                            Laid-Back Camp The Movie   2022-07-01      17.384                                                [Animation, Comedy]          0    7283918         7.500      121
59                                   Ranma ½: The Movie 2 — The Battle of Togenkyo: Rescue the Brides!   1992-08-02      39.016                                        [Action, Comedy, Animation]          0          0         8.000       63
60                                                     Pokémon the Movie: Black - Victini and Reshiram   2011-07-16      16.244                     [Animation, Family, Adventure, Drama, Fantasy]          0          0         6.600       96
61                                                            Grateful Dead Meet-Up At The Movies 2023   2023-06-22       3.803                                               [Documentary, Music]          0          0         0.000        0
62                                                                             Cowboy Bebop: The Movie   2001-09-01      16.944                               [Action, Animation, Science Fiction]          0          0         7.692      115
63                                                                              Psycho-Pass: The Movie   2015-01-09      10.628                               [Animation, Science Fiction, Action]          0          0         7.108      113
64                                                                  Pokémon the Movie: The Power of Us   2018-07-13      14.961                            [Animation, Family, Adventure, Fantasy]          0   23740788         7.100       98
65                                                                                Pokémon 3: The Movie   2000-07-08      17.642                    [Adventure, Fantasy, Animation, Action, Family]   16000000   68411275         6.503       74
66                                                                                  2gether: The Movie   2021-04-22      12.009                                                   [Drama, Romance]          0          0         7.900      107
67                                                                            Sekaiichi Hatsukoi Movie   2014-03-15       8.554                                        [Animation, Romance, Drama]          0          0         6.700       50
68                                          Gintama: The Movie: The Final Chapter: Be Forever Yorozuya   2013-07-04      15.727                       [Action, Comedy, Science Fiction, Animation]          0          0         8.000      110
69                                                              Sailor Moon S the Movie: Hearts in Ice   1994-12-04      27.284                      [Animation, Fantasy, Action, Romance, Comedy]          0    9940717         7.823       60
70                                                                Bleach the Movie: Memories of Nobody   2006-12-16      15.143                              [Fantasy, Animation, Science Fiction]          0    1238072         6.922       87
71                                                                             Cherry Magic! THE MOVIE   2022-04-08      23.381                                                  [Comedy, Romance]          0          0         7.000      104
72                                                      Haikyuu!! The Movie: The End and the Beginning   2015-07-03      11.148                                         [Animation, Comedy, Drama]          0          0         8.400       89
73                                             Fullmetal Alchemist the Movie: The Sacred Star of Milos   2011-07-02      11.455           [Adventure, Fantasy, Animation, Action, Science Fiction]          0    7401480         6.830      110
74                                                       Pokémon the Movie: White - Victini and Zekrom   2011-07-16      15.279                     [Animation, Family, Adventure, Drama, Fantasy]          0          0         6.600       96
75  Ranma ½: The Movie 3 — The Super Non-Discriminatory Showdown: Team Ranma vs. the Legendary Phoenix   1994-08-20      43.318                                                [Animation, Comedy]          0          0         7.700       35
76                                                         Bleach the Movie: The DiamondDust Rebellion   2007-12-22      15.894                                     [Action, Adventure, Animation]          0          0         6.717       95
77                                                               Street Fighter II: The Animated Movie   1994-08-06      18.465                                                [Animation, Action]          0          0         6.900      101
78                                                                             Just Like in the Movies   1989-10-04       1.020                                                    [Comedy, Drama]          0          0         8.000       92
79                                          Kuroko's Basketball - Movie: Winter Cup - Shadow and Light   2016-09-03       9.365                                                        [Animation]          0          0         6.700       90
80                                            Gurren Lagann the Movie: The Lights in the Sky Are Stars   2009-04-25      13.759                    [Action, Science Fiction, Animation, Adventure]          0          0         7.787      126
81                                                                     The House of Flowers: The Movie   2021-06-23      10.292                                                            [Drama]          0          0         8.000       86

In [52]:
print(df.shape)

(180, 8)

In [53]:
import numpy as np

In [54]:
df.head(5)

,title,release_date,popularity,genres,budget,revenue,vote_average,runtime
0,Movies,,1.546,[],0,0,4.2,0
1,Movies,,0.600,[],0,0,1.7,0
2,Sword Art Online the Movie -Progressive- Scher...,2022-10-22,247.353,"[Animation, Action, Fantasy, Science Fiction]",0,0,7.6,100
3,Movies,,0.600,[],0,0,0.0,0
4,"Miraculous: Ladybug & Cat Noir, The Movie",2023-07-05,304.840,"[Animation, Family, Action, Fantasy, Romance]",86000000,0,8.6,107

In [55]:
df['release_date'] = df['release_date'].fillna(np.nan)

In [56]:
df['release_date'].isna()

0      False
1      False
2      False
3      False
4      False
       ...
175    False
176    False
177    False
178    False
179    False
Name: release_date, Length: 180, dtype: bool

In [57]:
df['release_date'] = df['release_date'].replace('',np.nan)
df['release_date'].head()

0           NaN
1           NaN
2    2022-10-22
3           NaN
4    2023-07-05
Name: release_date, dtype: object

In [72]:

df = df.replace(0, np.nan)

df.head(20)

,title,release_date,popularity,genres,budget,revenue,vote_average,runtime
0,Movies,NaN,1.546,NaN,NaN,NaN,4.200,NaN
1,Movies,NaN,0.600,NaN,NaN,NaN,1.700,NaN
2,Sword Art Online the Movie -Progressive- Scher...,2022-10-22,247.353,"[Animation, Action, Fantasy, Science Fiction]",NaN,NaN,7.600,100.0
3,Movies,NaN,0.600,NaN,NaN,NaN,NaN,NaN
4,"Miraculous: Ladybug & Cat Noir, The Movie",2023-07-05,304.840,"[Animation, Family, Action, Fantasy, Romance]",86000000.0,NaN,8.600,107.0
5,Demon Slayer -Kimetsu no Yaiba- The Movie: Mug...,2020-10-16,132.360,"[Action, Animation, Adventure, Fantasy, Thriller]",15800000.0,503063688.0,8.256,117.0
6,That Time I Got Reincarnated as a Slime the Mo...,2022-11-25,138.136,"[Animation, Fantasy, Adventure]",NaN,11426555.0,7.600,108.0
7,The Quintessential Quintuplets Movie,2022-05-20,91.576,"[Animation, Comedy, Romance]",NaN,17288993.0,8.407,136.0
8,The Ten Commandments: The Movie,2016-01-28,26.888,[Drama],39307171.0,37070177.0,7.200,120.0
9,Naruto Shippuden the Movie,2007-08-04,79.180,"[Animation, Action, Fantasy]",NaN,10000000.0,7.274,94.0
10,The Last: Naruto the Movie,2014-12-06,51.872,"[Action, Romance, Animation]",903852.0,19840000.0,7.749,114.0
11,X-Rated: The Greatest Adult Movies of All Time,2015-02-06,39.319,[Documentary],NaN,NaN,6.147,94.0
12,Pokémon the Movie: Secrets of the Jungle,2020-12-25,40.206,"[Animation, Adventure, Family, Fantasy]",NaN,NaN,7.100,101.0
13,Boruto: Naruto the Movie,2015-08-07,49.800,"[Animation, Action, Comedy]",NaN,39500000.0,7.594,95.0
14,A Silent Voice: The Movie,2016-09-17,50.390,"[Animation, Drama]",NaN,30156463.0,8.400,130.0
15,Naruto Shippuden the Movie: Blood Prison,2011-07-30,45.508,"[Thriller, Animation, Action, Comedy, Horror, ...",NaN,9100000.0,7.292,108.0
16,"Easy Sex, Sad Movies",2014-10-16,9.055,[Comedy],NaN,NaN,5.500,90.0
17,Sailor Moon SuperS: The Movie: Black Dream Hole,1995-12-23,31.413,"[Animation, Fantasy, Action, Romance, Comedy]",NaN,NaN,8.100,60.0
18,Road to Ninja: Naruto the Movie,2012-07-28,46.581,"[Animation, Fantasy, Action]",NaN,17900000.0,7.576,109.0
19,Kuroko's Basketball the Movie: Last Game,2017-03-18,19.732,[Animation],NaN,NaN,7.745,90.0

In [59]:
df['genres'] = df['genres'].replace('[]',np.nan)
df['genres'].head()

0                                               []
1                                               []
2    [Animation, Action, Fantasy, Science Fiction]
3                                               []
4    [Animation, Family, Action, Fantasy, Romance]
Name: genres, dtype: object

In [66]:
df['genres'].dtypes

dtype('O')

In [69]:
print(df.genres)

0                                                NaN
1                                                NaN
2      [Animation, Action, Fantasy, Science Fiction]
3                                                NaN
4      [Animation, Family, Action, Fantasy, Romance]
                           ...
175                                        [Romance]
176                        [Animation, Drama, Music]
177                              [Action, Animation]
178                             [Music, Documentary]
179                       [Animation, Drama, Family]
Name: genres, Length: 180, dtype: object

In [68]:
import numpy as np
mask = df['genres'].apply(lambda x: len(x) == 0)
df.loc[mask, 'genres'] = np.nan

In [70]:
df.isnull().values.any()

True

In [71]:
df.isnull().sum()

title             0
release_date      3
popularity        0
genres            4
budget          161
revenue         135
vote_average      9
runtime          12
dtype: int64

In [73]:
df.isnull()

,title,release_date,popularity,genres,budget,revenue,vote_average,runtime
0,False,True,False,True,True,True,False,True
1,False,True,False,True,True,True,False,True
2,False,False,False,False,True,True,False,False
3,False,True,False,True,True,True,True,True
4,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...
175,False,False,False,False,True,True,True,False
176,False,False,False,False,True,True,False,False
177,False,False,False,False,True,True,False,False
178,False,False,False,False,True,False,False,False
179,False,False,False,False,True,True,False,False

In [74]:
df.isnull().sum()

title             0
release_date      3
popularity        0
genres            4
budget          161
revenue         135
vote_average      9
runtime          12
dtype: int64

In [75]:
df.isnull().sum(axis=1)

0      5
1      5
2      2
3      6
4      1
      ..
175    3
176    2
177    2
178    1
179    2
Length: 180, dtype: int64